# ==========================
# Stage 1 - Build
# ==========================
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

# Copy project files first
COPY . .

# Restore dependencies
RUN dotnet restore Web.csproj

# Publish application
RUN dotnet publish Web.csproj \
    -c Release \
    -o /app/publish \
    /p:UseAppHost=false

# ==========================
# Stage 2 - Runtime
# ==========================
FROM mcr.microsoft.com/dotnet/aspnet:9.0

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet","Web.dll"]